repos:

- repo: https://github.com/psf/black
  rev: 24.4.2   # Modify "blacken-docs" to point to this version
  hooks:
  - id: black

- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==24.4.2]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    exclude: "examples/"

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: ["--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt"]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: "tests/|examples/"

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.3.1
  hooks:
  - id: add-license-headers
    args:
    - --start_year=2022
