name: Nightly
on:
  push:
    branches:
      - "maint/nightly-tests"

jobs:
  test-suite:
    name: "Test suite"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ansys/optislang:23.2.0-jammy
      credentials:
        username: ansys-bot
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Pytest"
        env:
          PYOPTISLANG_DISABLE_OPTISLANG_OUTPUT: true
          ANSYSLMD_LICENSE_FILE: format("1055@{0}", ${{ secrets.LICENSE_SERVER }})
        uses: ansys/actions/tests-pytest@v4
        with:
          python-version: "3.10"
          use-python-cache: false
